In [3]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
import matplotlib.pyplot as plt

In [16]:
# Read in the data
df = pd.read_excel('e-commerce-dataset.xlsx', sheet_name='E_Comm')
df.to_csv('e-commerce_churn.csv', index=False)
df = pd.read_csv('e-commerce_churn.csv')
df.head()

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,3.0,3,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,50002,1,NaN,Phone,1,8.0,UPI,Male,3.0,4,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,50003,1,NaN,Phone,1,30.0,Debit Card,Male,2.0,4,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,50004,1,0.0,Phone,3,15.0,Debit Card,Male,2.0,4,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,50005,1,0.0,Phone,1,12.0,CC,Male,NaN,3,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60

In [9]:
df = df.dropna()

df['Churn'] = df['Churn'].astype('category')

# Identify non-numeric columns
non_numeric_cols = df.select_dtypes(include=['object']).columns

# Apply one-hot encoding to non-numeric columns
df = pd.get_dummies(df, columns=non_numeric_cols, drop_first=True)

print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 3774 entries, 0 to 5629
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   CustomerID                             3774 non-null   int64
 1   Churn                                  3774 non-null   category
 2   Tenure                                 3774 non-null   float64
 3   CityTier                               3774 non-null   int64
 4   WarehouseToHome                        3774 non-null   float64
 5   HourSpendOnApp                         3774 non-null   float64
 6   NumberOfDeviceRegistered               3774 non-null   int64
 7   SatisfactionScore                      3774 non-null   int64
 8   NumberOfAddress                        3774 non-null   int64
 9   Complain                               3774 non-null   int64
 10  OrderAmountHikeFromlastYear            3774 non-null   float64
 11  CouponUsed                             3774 non-null   float64
 12  OrderCount                             3774 non-null   float64
 13  DaySinceLastOrder                      3774 non-null   float64
 14  CashbackAmount                         3774 non-null   float64
 15  PreferredLoginDevice_Mobile Phone      3774 non-null   bool
 16  PreferredLoginDevice_Phone             3774 non-null   bool
 17  PreferredPaymentMode_COD               3774 non-null   bool
 18  PreferredPaymentMode_Cash on Delivery  3774 non-null   bool
 19  PreferredPaymentMode_Credit Card       3774 non-null   bool
 20  PreferredPaymentMode_Debit Card        3774 non-null   bool
 21  PreferredPaymentMode_E wallet          3774 non-null   bool
 22  PreferredPaymentMode_UPI               3774 non-null   bool
 23  Gender_Male                            3774 non-null   bool
 24  PreferedOrderCat_Grocery               3774 non-null   bool
 25  PreferedOrderCat_Laptop & Accessory    3774 non-null   bool
 26  PreferedOrderCat_Mobile                3774 non-null   bool
 27  PreferedOrderCat_Mobile Phone          3774 non-null   bool
 28  PreferedOrderCat_Others                3774 non-null   bool
 29  MaritalStatus_Married                  3774 non-null   bool
 30  MaritalStatus_Single                   3774 non-null   bool
dtypes: bool(16), category(1), float64(8), int64(6)
memory usage: 505.0 KB
None

In [13]:
#random forest model
X = df.drop(columns=['Churn'])
y = y = df['Churn']

      CustomerID  Tenure  CityTier  WarehouseToHome  HourSpendOnApp  \
0          50001     4.0         3              6.0             3.0
3          50004     0.0         3             15.0             2.0
5          50006     0.0         1             22.0             3.0
11         50012    11.0         1              6.0             3.0
12         50013     0.0         1             11.0             2.0
...          ...     ...       ...              ...             ...
5624       55625     1.0         3             12.0             2.0
5625       55626    10.0         1             30.0             3.0
5627       55628     1.0         1             11.0             3.0
5628       55629    23.0         3              9.0             4.0
5629       55630     8.0         1             15.0             3.0

      NumberOfDeviceRegistered  SatisfactionScore  NumberOfAddress  Complain  \
0                            3                  2                9         1
3                            4                  5                8         0
5                            5                  5                2         1
11                           4                  3               10         1
12                           3                  3                2         1
...                        ...                ...              ...       ...
5624                         5                  3                2         0
5625                         2                  1                6         0
5627                         2                  4                3         1
5628                         5                  4                4         0
5629                         2                  3                4         0

      OrderAmountHikeFromlastYear  ...  PreferredPaymentMode_E wallet  \
0                            11.0  ...                          False
3                            23.0  ...                          False
5                            22.0  ...                          False
11                           13.0  ...                          False
12                           13.0  ...                          False
...                           ...  ...                            ...
5624                         19.0  ...                          False
5625                         18.0  ...                          False
5627                         21.0  ...                          False
5628                         15.0  ...                          False
5629                         13.0  ...                          False

      PreferredPaymentMode_UPI  Gender_Male  PreferedOrderCat_Grocery  \
0                        False        False                     False
3                        False         True                     False
5                        False        False                     False
11                       False         True                     False
12                       False         True                     False
...                        ...          ...                       ...
5624                      True        False                     False
5625                     False         True                     False
5627                     False         True                     False
5628                     False         True                     False
5629                     False         True                     False

      PreferedOrderCat_Laptop & Accessory  PreferedOrderCat_Mobile  \
0                                    True                    False
3                                    True                    False
5                                   False                    False
11                                  False                    False
12                                  False                     True
...                                   ...                      ...
5624                                False                    False
5625                                 True                    False
5627                                 True                    False
5628                                 True                    False
5629                                 True                    False

      PreferedOrderCat_Mobile Phone  PreferedOrderCat_Others  \
0                             False                    False
3                             False                    False
5                              True                    False
11                            False                    False
12                            False                    False
...                             ...                      ...
5624                           True                    False
5625                          False                    False
5627                          False                    False
5628                          False                    False
5629                          False                    False

      MaritalStatus_Married  MaritalStatus_Single
0                     False                  True
3                     False                  True
5                     False                  True
11                    False                  True
12                    False                  True
...                     ...                   ...
5624                  False                  True
5625                   True                 False
5627                   True                 False
5628                   True                 False
5629                   True                 False

[3774 rows x 30 columns]

In [18]:
#train test split
train_df, test_df = train_test_split(df , test_size=0.20, stratify=df['Churn'], random_state=2023+2024)

# View proportions of Churn
print(f"Proportions Train:\n {train_df['Churn'].value_counts(normalize=True)}")
print(f"Proportions Test:\n {test_df['Churn'].value_counts(normalize=True)}")

Proportions Train:
 Churn
0    0.831705
1    0.168295
Name: proportion, dtype: float64
Proportions Test:
 Churn
0    0.831261
1    0.168739
Name: proportion, dtype: float64

In [20]:
#define model
train_model = RandomForestClassifier(n_estimators=1000, max_features=3, random_state=0)
# Cross-validation
cv_fits_accuracy = cross_val_score(train_model, X, y, cv=4, scoring='accuracy')
cv_fits_precision = cross_val_score(train_model, X, y, cv=4, scoring='precision')
cv_fits_recall = cross_val_score(train_model, X, y, cv=4, scoring='recall')
print("\nCV-Accuracy:", np.mean(cv_fits_accuracy))
print("CV-Precision:", np.mean(cv_fits_precision))
print("CV-Recall:", np.mean(cv_fits_recall))

CV-Accuracy: 0.956823921131621
CV-Precision: 0.982445987654321
CV-Recall: 0.7594634362654196